version: "3.8"
services:
  db:
    image: postgres:16.0-alpine
    container_name: sound_lock_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    # ports:
    #   - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: sound_lock_app
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path=/migrations",
        "-database=postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?sslmode=disable",
        "up",
      ]
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
