// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handlers/profile/handlers.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	models "sound_lock/internal/domain/models"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockProfileService is a mock of ProfileService interface.
type MockProfileService struct {
	ctrl     *gomock.Controller
	recorder *MockProfileServiceMockRecorder
}

// MockProfileServiceMockRecorder is the mock recorder for MockProfileService.
type MockProfileServiceMockRecorder struct {
	mock *MockProfileService
}

// NewMockProfileService creates a new mock instance.
func NewMockProfileService(ctrl *gomock.Controller) *MockProfileService {
	mock := &MockProfileService{ctrl: ctrl}
	mock.recorder = &MockProfileServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileService) EXPECT() *MockProfileServiceMockRecorder {
	return m.recorder
}

// ChangeProfileUser mocks base method.
func (m *MockProfileService) ChangeProfileUser(ctx context.Context, userDTO models.UserDTO) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeProfileUser", ctx, userDTO)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeProfileUser indicates an expected call of ChangeProfileUser.
func (mr *MockProfileServiceMockRecorder) ChangeProfileUser(ctx, userDTO interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeProfileUser", reflect.TypeOf((*MockProfileService)(nil).ChangeProfileUser), ctx, userDTO)
}

// ProfileUser mocks base method.
func (m *MockProfileService) ProfileUser(ctx context.Context, userID uuid.UUID) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProfileUser", ctx, userID)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProfileUser indicates an expected call of ProfileUser.
func (mr *MockProfileServiceMockRecorder) ProfileUser(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProfileUser", reflect.TypeOf((*MockProfileService)(nil).ProfileUser), ctx, userID)
}
