// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/profile.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	models "sound_lock/internal/domain/models"

	gomock "github.com/golang/mock/gomock"
)

// MockProfileProvider is a mock of ProfileProvider interface.
type MockProfileProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProfileProviderMockRecorder
}

// MockProfileProviderMockRecorder is the mock recorder for MockProfileProvider.
type MockProfileProviderMockRecorder struct {
	mock *MockProfileProvider
}

// NewMockProfileProvider creates a new mock instance.
func NewMockProfileProvider(ctrl *gomock.Controller) *MockProfileProvider {
	mock := &MockProfileProvider{ctrl: ctrl}
	mock.recorder = &MockProfileProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileProvider) EXPECT() *MockProfileProviderMockRecorder {
	return m.recorder
}

// ReadUserByID mocks base method.
func (m *MockProfileProvider) ReadUserByID(ctx context.Context, userID string) (models.UserDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadUserByID", ctx, userID)
	ret0, _ := ret[0].(models.UserDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadUserByID indicates an expected call of ReadUserByID.
func (mr *MockProfileProviderMockRecorder) ReadUserByID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadUserByID", reflect.TypeOf((*MockProfileProvider)(nil).ReadUserByID), ctx, userID)
}

// UpdateUser mocks base method.
func (m *MockProfileProvider) UpdateUser(ctx context.Context, userDTO models.UserDTO) (models.UserDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, userDTO)
	ret0, _ := ret[0].(models.UserDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockProfileProviderMockRecorder) UpdateUser(ctx, userDTO interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockProfileProvider)(nil).UpdateUser), ctx, userDTO)
}
