// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/auth.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	models "sound_lock/internal/domain/models"
	jwt "sound_lock/internal/lib/jwt"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockJWTMethods is a mock of JWTMethods interface.
type MockJWTMethods struct {
	ctrl     *gomock.Controller
	recorder *MockJWTMethodsMockRecorder
}

// MockJWTMethodsMockRecorder is the mock recorder for MockJWTMethods.
type MockJWTMethodsMockRecorder struct {
	mock *MockJWTMethods
}

// NewMockJWTMethods creates a new mock instance.
func NewMockJWTMethods(ctrl *gomock.Controller) *MockJWTMethods {
	mock := &MockJWTMethods{ctrl: ctrl}
	mock.recorder = &MockJWTMethodsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTMethods) EXPECT() *MockJWTMethodsMockRecorder {
	return m.recorder
}

// GenerateAccessToken mocks base method.
func (m *MockJWTMethods) GenerateAccessToken(userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAccessToken", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateAccessToken indicates an expected call of GenerateAccessToken.
func (mr *MockJWTMethodsMockRecorder) GenerateAccessToken(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAccessToken", reflect.TypeOf((*MockJWTMethods)(nil).GenerateAccessToken), userID)
}

// GenerateRefreshToken mocks base method.
func (m *MockJWTMethods) GenerateRefreshToken(userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRefreshToken", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateRefreshToken indicates an expected call of GenerateRefreshToken.
func (mr *MockJWTMethodsMockRecorder) GenerateRefreshToken(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRefreshToken", reflect.TypeOf((*MockJWTMethods)(nil).GenerateRefreshToken), userID)
}

// ParseAccessToken mocks base method.
func (m *MockJWTMethods) ParseAccessToken(tokenString string) (*jwt.TokenClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseAccessToken", tokenString)
	ret0, _ := ret[0].(*jwt.TokenClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseAccessToken indicates an expected call of ParseAccessToken.
func (mr *MockJWTMethodsMockRecorder) ParseAccessToken(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseAccessToken", reflect.TypeOf((*MockJWTMethods)(nil).ParseAccessToken), tokenString)
}

// ParseRefreshToken mocks base method.
func (m *MockJWTMethods) ParseRefreshToken(tokenString string) (*jwt.TokenClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseRefreshToken", tokenString)
	ret0, _ := ret[0].(*jwt.TokenClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseRefreshToken indicates an expected call of ParseRefreshToken.
func (mr *MockJWTMethodsMockRecorder) ParseRefreshToken(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseRefreshToken", reflect.TypeOf((*MockJWTMethods)(nil).ParseRefreshToken), tokenString)
}

// MockUserSaver is a mock of UserSaver interface.
type MockUserSaver struct {
	ctrl     *gomock.Controller
	recorder *MockUserSaverMockRecorder
}

// MockUserSaverMockRecorder is the mock recorder for MockUserSaver.
type MockUserSaverMockRecorder struct {
	mock *MockUserSaver
}

// NewMockUserSaver creates a new mock instance.
func NewMockUserSaver(ctrl *gomock.Controller) *MockUserSaver {
	mock := &MockUserSaver{ctrl: ctrl}
	mock.recorder = &MockUserSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserSaver) EXPECT() *MockUserSaverMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserSaver) CreateUser(ctx context.Context, email, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, email, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserSaverMockRecorder) CreateUser(ctx, email, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserSaver)(nil).CreateUser), ctx, email, password)
}

// MockUserProvider is a mock of UserProvider interface.
type MockUserProvider struct {
	ctrl     *gomock.Controller
	recorder *MockUserProviderMockRecorder
}

// MockUserProviderMockRecorder is the mock recorder for MockUserProvider.
type MockUserProviderMockRecorder struct {
	mock *MockUserProvider
}

// NewMockUserProvider creates a new mock instance.
func NewMockUserProvider(ctrl *gomock.Controller) *MockUserProvider {
	mock := &MockUserProvider{ctrl: ctrl}
	mock.recorder = &MockUserProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserProvider) EXPECT() *MockUserProviderMockRecorder {
	return m.recorder
}

// ReadUser mocks base method.
func (m *MockUserProvider) ReadUser(ctx context.Context, email string) (models.UserDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadUser", ctx, email)
	ret0, _ := ret[0].(models.UserDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadUser indicates an expected call of ReadUser.
func (mr *MockUserProviderMockRecorder) ReadUser(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadUser", reflect.TypeOf((*MockUserProvider)(nil).ReadUser), ctx, email)
}

// MockRefreshTokenSaver is a mock of RefreshTokenSaver interface.
type MockRefreshTokenSaver struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenSaverMockRecorder
}

// MockRefreshTokenSaverMockRecorder is the mock recorder for MockRefreshTokenSaver.
type MockRefreshTokenSaverMockRecorder struct {
	mock *MockRefreshTokenSaver
}

// NewMockRefreshTokenSaver creates a new mock instance.
func NewMockRefreshTokenSaver(ctrl *gomock.Controller) *MockRefreshTokenSaver {
	mock := &MockRefreshTokenSaver{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenSaver) EXPECT() *MockRefreshTokenSaverMockRecorder {
	return m.recorder
}

// CreateRefreshToken mocks base method.
func (m *MockRefreshTokenSaver) CreateRefreshToken(ctx context.Context, userID, token string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefreshToken", ctx, userID, token, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRefreshToken indicates an expected call of CreateRefreshToken.
func (mr *MockRefreshTokenSaverMockRecorder) CreateRefreshToken(ctx, userID, token, expiresAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefreshToken", reflect.TypeOf((*MockRefreshTokenSaver)(nil).CreateRefreshToken), ctx, userID, token, expiresAt)
}

// MockRefreshTokenProvider is a mock of RefreshTokenProvider interface.
type MockRefreshTokenProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenProviderMockRecorder
}

// MockRefreshTokenProviderMockRecorder is the mock recorder for MockRefreshTokenProvider.
type MockRefreshTokenProviderMockRecorder struct {
	mock *MockRefreshTokenProvider
}

// NewMockRefreshTokenProvider creates a new mock instance.
func NewMockRefreshTokenProvider(ctrl *gomock.Controller) *MockRefreshTokenProvider {
	mock := &MockRefreshTokenProvider{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenProvider) EXPECT() *MockRefreshTokenProviderMockRecorder {
	return m.recorder
}

// UpdateRefreshToken mocks base method.
func (m *MockRefreshTokenProvider) UpdateRefreshToken(ctx context.Context, userID, token, oldToken string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRefreshToken", ctx, userID, token, oldToken, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRefreshToken indicates an expected call of UpdateRefreshToken.
func (mr *MockRefreshTokenProviderMockRecorder) UpdateRefreshToken(ctx, userID, token, oldToken, expiresAt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRefreshToken", reflect.TypeOf((*MockRefreshTokenProvider)(nil).UpdateRefreshToken), ctx, userID, token, oldToken, expiresAt)
}

// MockRefreshTokenRemover is a mock of RefreshTokenRemover interface.
type MockRefreshTokenRemover struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenRemoverMockRecorder
}

// MockRefreshTokenRemoverMockRecorder is the mock recorder for MockRefreshTokenRemover.
type MockRefreshTokenRemoverMockRecorder struct {
	mock *MockRefreshTokenRemover
}

// NewMockRefreshTokenRemover creates a new mock instance.
func NewMockRefreshTokenRemover(ctrl *gomock.Controller) *MockRefreshTokenRemover {
	mock := &MockRefreshTokenRemover{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenRemoverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenRemover) EXPECT() *MockRefreshTokenRemoverMockRecorder {
	return m.recorder
}

// DeleteRefreshToken mocks base method.
func (m *MockRefreshTokenRemover) DeleteRefreshToken(ctx context.Context, userID, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefreshToken", ctx, userID, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefreshToken indicates an expected call of DeleteRefreshToken.
func (mr *MockRefreshTokenRemoverMockRecorder) DeleteRefreshToken(ctx, userID, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefreshToken", reflect.TypeOf((*MockRefreshTokenRemover)(nil).DeleteRefreshToken), ctx, userID, token)
}
