name: CI & Deploy on PR merge to master

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.4"

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./... -v -cover

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3

      # Копируем проект на сервер (без .env)
      - name: Copy project to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./
          target: /root/app/sound-lock

      # Создаём .env на сервере из GitHub Secrets
      - name: Create .env on server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cat <<EOF > /root/app/sound-lock/.env
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_NAME=${{ secrets.DB_NAME }}
            ACCESS_TOKEN_SIGNING_KEY=${{ secrets.ACCESS_TOKEN_SIGNING_KEY }}
            REFRESH_TOKEN_SIGNING_KEY=${{ secrets.REFRESH_TOKEN_SIGNING_KEY }}
            SSL_MODE=disable
            EOF

      # Перезапуск контейнеров
      - name: Deploy on VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/app/sound-lock
            docker-compose down || true
            docker-compose up -d --build

      # Миграции
      - name: Run migrations
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/app/sound-lock
            export $(cat .env | xargs)
            docker run --rm \
              -v $(pwd)/migrations:/migrations \
              --network host \
              migrate/migrate \
              -path=/migrations \
              -database "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable" up
